name: Build macOS

on:
  push:
    branches:
      - main

jobs:
  build-macos:

    runs-on: macos-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4


      #
      # ARM64
      #

      - name: Install ARM64 dependencies
        run: |
          arch -arm64 brew install sfml taglib


      - name: Build ARM64
        working-directory: src
        run: |
          make clean
          make -f Makefile.macos ARCHS="-arch arm64" BREW_PREFIX=/opt/homebrew

          mv builds/mishplayer builds/mishplayer-arm64.bin



      #
      # Intel
      #

      - name: Install Rosetta
        run: |
          sudo softwareupdate --install-rosetta --agree-to-license


      - name: Install Intel Homebrew
        run: |
          arch -x86_64 /bin/bash -c \
          "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"


      - name: Install Intel dependencies
        run: |
          arch -x86_64 /usr/local/bin/brew install sfml taglib



      - name: Build x86_64
        working-directory: src
        run: |
          make clean
          make -f Makefile.macos ARCHS="-arch x86_64" BREW_PREFIX=/usr/local

          mv builds/mishplayer builds/mishplayer-x86_64.bin



      #
      # Universal executable
      #

      - name: Create Universal Binary
        working-directory: src
        run: |
          lipo \
            -create \
            builds/mishplayer-arm64.bin \
            builds/mishplayer-x86_64.bin \
            -output builds/mishplayer



      - name: Verify executable
        working-directory: src
        run: |
          file builds/mishplayer
          lipo -info builds/mishplayer



      #
      # Universal libraries
      #

      - name: Create Universal dylibs
        run: |

          mkdir -p universal-libs


          lipo \
            /opt/homebrew/lib/libsfml-graphics.dylib \
            /usr/local/lib/libsfml-graphics.dylib \
            -create \
            -output universal-libs/libsfml-graphics.dylib


          lipo \
            /opt/homebrew/lib/libsfml-window.dylib \
            /usr/local/lib/libsfml-window.dylib \
            -create \
            -output universal-libs/libsfml-window.dylib


          lipo \
            /opt/homebrew/lib/libsfml-audio.dylib \
            /usr/local/lib/libsfml-audio.dylib \
            -create \
            -output universal-libs/libsfml-audio.dylib


          lipo \
            /opt/homebrew/lib/libsfml-system.dylib \
            /usr/local/lib/libsfml-system.dylib \
            -create \
            -output universal-libs/libsfml-system.dylib


          lipo \
            /opt/homebrew/lib/libtag.dylib \
            /usr/local/lib/libtag.dylib \
            -create \
            -output universal-libs/libtag.dylib



      - name: Verify dylibs
        run: |
          file universal-libs/*.dylib



      #
      # Create .app
      #

      - name: Create App Bundle
        run: |

          mkdir -p release/MishPlayer.app/Contents/MacOS
          mkdir -p release/MishPlayer.app/Contents/Frameworks
          mkdir -p release/MishPlayer.app/Contents/Resources


          cp src/builds/mishplayer \
          release/MishPlayer.app/Contents/MacOS/



          cp universal-libs/*.dylib \
          release/MishPlayer.app/Contents/Frameworks/



          cp -r assets/* \
          release/MishPlayer.app/Contents/Resources/



          cat > release/MishPlayer.app/Contents/Info.plist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>

            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

            <plist version="1.0">

            <dict>

                <key>CFBundleName</key>
                <string>Mish Player</string>

                <key>CFBundleDisplayName</key>
                <string>Mish Player</string>

                <key>CFBundleIdentifier</key>
                <string>com.mish.player</string>

                <key>CFBundleExecutable</key>
                <string>mishplayer</string>

                <key>CFBundlePackageType</key>
                <string>APPL</string>

                <key>LSMinimumSystemVersion</key>
                <string>11.0</string>

            </dict>

            </plist>
            EOF

      #
      # Fix dylib lookup
      #

      - name: Fix dylib paths
        run: |

          install_name_tool \
          -add_rpath \
          "@executable_path/../Frameworks" \
          release/MishPlayer.app/Contents/MacOS/mishplayer


          for lib in release/MishPlayer.app/Contents/Frameworks/*.dylib
          do
            install_name_tool \
            -id \
            "@rpath/$(basename $lib)" \
            "$lib"
          done



      #
      # Final check
      #

      - name: Verify App
        run: |

          file release/MishPlayer.app/Contents/MacOS/mishplayer

          otool -L \
          release/MishPlayer.app/Contents/MacOS/mishplayer



      #
      # Upload
      #

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: mish-macos-universal-app
          path: release/